FORMAT: 1A
HOST: https://football.apiblueprint.org/

# FootballAPI

FootballAPI is a simple API allowing consumers query information on football matches and players.
This first version will focus on the matches of FCPorto.

## Teams Collection [/v1/teams]

### Get all Teams [GET]

+ Response 200 (application/json)

        [
            {
                "teams":[
                {
                    "name": "Futebol Clube do Porto",
                    "shortName": "FCP",
                    "website": "http://www.fcp.pt",
                    "email": "info@",
                    "founded": 1896,
                    "clubColors": "Azul e Branco",
                    "venue": "Estadio do Dragao",
                    "id":1
                },
                {
                    "name": "Liverpool",
                    "shortName": "LFC",
                    "website": "http://www.lfc.com",
                    "email": "info@",
                    "founded": 1900,
                    "clubColors": "Red",
                    "venue": "Anfield Road",
                    "id":2
                }
            }    
        ]

## Players Collection [/v1/players/{id}]

### Get all Players for a Team [GET]

+ Response 200 (application/json)

        [
            {
                "id":1,
                "players": [
                    {
                        "id": 1,
                        "name": "Marchesin",
                        "position":"GK"
                    }, {
                        "id": 2,
                        "name": "Pepe",
                        "position":"DC"
                    }, {
                        "id": 3,
                        "name": "Marega",
                        "position":"AV"
                    }, {
                        "id": 2,
                        "name": "Corona",
                        "position":"AVD"
                    }
                ]
            }
        ]

## Matches Collection [/v1/matches/{id}]

+ Parameters

    + id: 1 (number) - An unique identifier of the message.
    
### Get all Matches for a Team [GET]

+ Response 200 (application/json)

        [
            {
                
                "matches": [
                    {
                        "id": 1,
                        "date": 2048,
                        "hometeam":"FCP",
                        "awayteam":"SCP",
                        "result":"1-1",
                        "HTresult":"1-0",
                        "scorer":"Marega(38),Sporar(56)"
                    }, {
                        "id": 1,
                        "date": 2048,
                        "hometeam":"FCP",
                        "awayteam":"SCP",
                        "result":"1-1",
                        "HTresult":"1-0",
                        "scorer":"Marega(38),Sporar(56)"
                    }
                ]
            }
        ]

### Create a New Match [POST]

You may create your own match using this action. It takes a JSON
object containing the match result.

+ Request (application/json)

        {
            "id": 1,
            "date": 2048,
            "hometeam":"FCP",
            "awayteam":"SCP",
            "result":"1-1",
            "HTresult":"1-0",
            "scorer":"Marega(38),Sporar(56)"
            
        }

+ Response 201 (application/json)

    + Headers

            Location: /matches/2

    + Body

            {
                "status": "All good",
                "published_at": "2015-08-05T08:40:51.620Z",
                
            }